[package]
name = "djtool"
version = "0.1.0"
edition = "2018"
# links = ["avutil"]

[profile.release]
opt-level = 's'  # Optimize for size.
lto = true # Link Time Optimization (LTO)

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffmpeg-next = "4.4.0-next.2"
reqwest = { version = "0.11.6", features = ["json", "blocking", "default-tls", "stream"] }
anyhow = "1.0"
async-trait = "0.1.51"
regex = "1.5"
lazy_static = "1.4.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
tokio = { version = "1.14.0", features = ["full"] }
sanitize-filename = "0.3.0"
rand = "0.8.4"
futures-util = "0.3.13"
url = "2.2.2"
rayon = "1.5.1"
Boa = "0.13.0"
futures = "0.3.17"
num_cpus = "1.13.0"
num = "0.4"

# [target.x86_64-unknown-linux-gnu.ffmpeg]
# [ffmpeg]
# rustc-link-search = ["target/native/lib"]
