[package]
name = "djtool"
version = "0.1.0"
edition = "2021"
# edition = "2018"

# Disable doctests as a workaround for https://github.com/rust-lang/rust-bindgen/issues/1313
doctest = false

[profile.release]
# opt-level = 's'  # Optimize for size.
lto = true # Link Time Optimization (LTO)

[dependencies]
reqwest = { version = "0.11.6", features = ["json", "blocking", "default-tls", "stream"] }
anyhow = "1.0"
async-trait = "0.1.51"
regex = "1.5"
lazy_static = "1.4.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
tokio = { version = "1.14.0", features = ["full"] }
tokio-stream = "0.1.8"
sanitize-filename = "0.3.0"
rand = "0.8.4"
futures-util = "0.3.13"
rustfft = "6.0.1"
approx = "0.5"
url = "2.2.2"
rayon = "1.5.1"
rodio = "0.15.0"
ndarray = { version = "0.15.4" , features = ["approx", "rayon"]}
Boa = "0.13.0"
futures = "0.3.17"
num_cpus = "1.13.0"
num = "0.4"
http = "0.2.5"
tempdir = "0.3.7"
libc = "0.2"
bitflags = "1.2"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde", "rustc-serialize"] }
thiserror = "1.0.30"
sha2 = "0.9.6"
webbrowser = "0.5.5"
warp = "0.3.2"
tauri = { version = "1.0.0-beta.8", features = ["custom-protocol"] , optional = true}
dirs = "4.0.0"
rspotify-model = "0.11.3"
async-stream = "0.3.2"
id3 = "0.6.6"
image = "0.23.14"
tonic = "0.5"
tonic-web = "0.1"
prost = "0.8"
prost-types = "0.8"

[build-dependencies]
anyhow = "1.0"
num_cpus   = "1.13"
cc         = "1.0"
pkg-config = "0.3"
lazy_static = "1.4.0"
bindgen    = { version = "0.59.2", default-features = false, features = ["runtime"] }
tauri-build = { version = "1.0.0-beta.4", optional = true }
tonic-build = { version = "0.5", features = ["prost"], optional = true }
rayon = { version = "1.5.1", optional=true }
crossbeam-channel = { version = "0.4", optional = true }

[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2"

[features]
default  = [
  "parallel-build",
  "proto-build",
  "ffmpeg",
  "gui",
]

gui = ["tauri", "tauri-build"]
proto-build = ["tonic-build"]

# ffmpeg libraries
ffmpeg = [
  "ffmpeg-avcodec",
  "ffmpeg-avdevice",
  "ffmpeg-avfilter",
  "ffmpeg-avformat",
  "ffmpeg-swresample",
  "ffmpeg-swscale",
  # additional ffmpeg decoders and encoders
  "ffmpeg-mp3lame",
  "ffmpeg-license-nonfree",
]

# force rebuilding ffmpeg
force-build = []

# parallel dependency graph iterator to build dependencies in parallel
parallel-build = ["rayon", "crossbeam-channel"]

# tauri
# custom-protocol = [ "tauri/custom-protocol" ]

# licensing
ffmpeg-license-gpl      = []
ffmpeg-license-nonfree  = []
ffmpeg-license-version3 = []

# misc
ffmpeg-drm   = []
ffmpeg-nvenc = []
ffmpeg-pic   = []
ffmpeg-zlib  = []

# ssl
ffmpeg-gnutls  = []
ffmpeg-openssl = []

# filters
ffmpeg-fontconfig = []
ffmpeg-frei0r     = []
ffmpeg-ladspa     = []
ffmpeg-ass        = []
ffmpeg-freetype   = []
ffmpeg-freebidi   = []
ffmpeg-opencv     = []
ffmpeg-vmaf       = []

# encoders/decoders
ffmpeg-aacplus          = []
ffmpeg-celt             = []
ffmpeg-dav1d            = []
ffmpeg-dcadec           = []
ffmpeg-faac             = []
ffmpeg-fdk-aac          = []
ffmpeg-gsm              = []
ffmpeg-ilbc             = []
ffmpeg-kvazaar          = []
ffmpeg-mp3lame          = []
ffmpeg-opencore-amrnb   = []
ffmpeg-opencore-amrwb   = []
ffmpeg-openh264         = []
ffmpeg-openjpeg         = []
ffmpeg-opus             = []
ffmpeg-schroedinger     = []
ffmpeg-shine            = []
ffmpeg-snappy           = []
ffmpeg-speex            = []
ffmpeg-stagefright-h264 = []
ffmpeg-theora           = []
ffmpeg-twolame          = []
ffmpeg-utvideo          = []
ffmpeg-vo-aacenc        = []
ffmpeg-vo-amrwbenc      = []
ffmpeg-vorbis           = []
ffmpeg-vpx              = []
ffmpeg-wavpack          = []
ffmpeg-webp             = []
ffmpeg-x264             = []
ffmpeg-x265             = []
ffmpeg-avs              = []
ffmpeg-xvid             = []

# protocols
ffmpeg-smbclient = []
ffmpeg-ssh       = []

# components
ffmpeg-avcodec    = []
ffmpeg-avdevice   = ["ffmpeg-avformat"]
ffmpeg-avfilter   = []
ffmpeg-avformat   = ["ffmpeg-avcodec"]
ffmpeg-avresample = []
ffmpeg-postproc   = []
ffmpeg-swresample = []
ffmpeg-swscale    = []
