[package]
name = "djtool"
version = "0.1.0"
edition = "2021"

[profile.release]
# opt-level = 's'  # Optimize for size.
lto = true # Link Time Optimization (LTO)

[dependencies]
# ffmpeg-next = { version = "4.4.0-next.2", features = ["build"] }
# , "avcodec", "avdevice", "avfilter", "avformat", "swresample", "swscale"] }
reqwest = { version = "0.11.6", features = ["json", "blocking", "default-tls", "stream"] }
anyhow = "1.0"
async-trait = "0.1.51"
regex = "1.5"
lazy_static = "1.4.0"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.71"
tokio = { version = "1.14.0", features = ["full"] }
sanitize-filename = "0.3.0"
rand = "0.8.4"
futures-util = "0.3.13"
url = "2.2.2"
rayon = "1.5.1"
Boa = "0.13.0"
futures = "0.3.17"
num_cpus = "1.13.0"
num = "0.4"
http = "0.2.5"
tempdir = "0.3.7"
libc = "0.2"

[build-dependencies]
anyhow = "1.0"
num_cpus   = "1.13"
cc         = "1.0"
pkg-config = "0.3"
bindgen    = { version = "0.59", default-features = false, features = ["runtime"] }

rayon = { version = "1.5.1", optional=true }
crossbeam-channel = { version = "0.4", optional = true }

[target.'cfg(target_env = "msvc")'.build-dependencies]
vcpkg = "0.2"

[features]
default  = ["parallel-build", "avcodec", "avdevice", "avfilter", "avformat", "swresample", "swscale"]

parallel-build = ["rayon", "crossbeam-channel"]

# static = []
# build  = ["static"]

# licensing
build-license-gpl      = []
build-license-nonfree  = []
build-license-version3 = []

# misc
build-drm   = []
build-nvenc = []
build-pic   = []
build-zlib  = []

# ssl
build-lib-gnutls  = []
build-lib-openssl = []

# filters
build-lib-fontconfig = []
build-lib-frei0r     = []
build-lib-ladspa     = []
build-lib-ass        = []
build-lib-freetype   = []
build-lib-freebidi   = []
build-lib-opencv     = []
build-lib-vmaf       = []

# encoders/decoders
build-lib-aacplus          = []
build-lib-celt             = []
build-lib-dav1d            = []
build-lib-dcadec           = []
build-lib-faac             = []
build-lib-fdk-aac          = []
build-lib-gsm              = []
build-lib-ilbc             = []
build-lib-kvazaar          = []
build-lib-mp3lame          = []
build-lib-opencore-amrnb   = []
build-lib-opencore-amrwb   = []
build-lib-openh264         = []
build-lib-openjpeg         = []
build-lib-opus             = []
build-lib-schroedinger     = []
build-lib-shine            = []
build-lib-snappy           = []
build-lib-speex            = []
build-lib-stagefright-h264 = []
build-lib-theora           = []
build-lib-twolame          = []
build-lib-utvideo          = []
build-lib-vo-aacenc        = []
build-lib-vo-amrwbenc      = []
build-lib-vorbis           = []
build-lib-vpx              = []
build-lib-wavpack          = []
build-lib-webp             = []
build-lib-x264             = []
build-lib-x265             = []
build-lib-avs              = []
build-lib-xvid             = []

# protocols
build-lib-smbclient = []
build-lib-ssh       = []

# components
avcodec    = []
avdevice   = ["avformat"]
avfilter   = []
avformat   = ["avcodec"]
avresample = []
postproc   = []
swresample = []
swscale    = []
