[package]
name = "djtool"
version = "0.1.0"
edition = "2018"
# links = ["avutil"]

[profile.release]
opt-level = 's'  # Optimize for size.
lto = true # Link Time Optimization (LTO)

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ffmpeg-next = "4.4.0-next.2"

# [target.x86_64-unknown-linux-gnu.ffmpeg]
# [ffmpeg]
# rustc-link-search = ["target/native/lib"]
